services:
  bookstack_db:
    image: mysql:8.0
    container_name: bookstack_db
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=bookstackdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=supersecret
    volumes:
      - ./resources/bookstack_db:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: unless-stopped

  bookstack_app:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack_app
    depends_on:
      - bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_DATABASE=bookstackdb
      - DB_USERNAME=admin
      - DB_PASSWORD=supersecret
      - APP_URL=http://localhost:8080
      - APP_KEY=base64:Gnka9bDDBnDrJmeBn7OgE5iJ4Y//sBUkfGgyBDWoYeQ=
    volumes:
      - ./resources/bookstack:/config
    ports:
      - "8080:80"
    restart: unless-stopped

  ackee_db:
    image: mongo:5
    container_name: ackee_db
    volumes:
      - ./resources/ackee_db:/data/db
    restart: unless-stopped

  ackee_app:
    image: electerious/ackee:latest
    container_name: ackee_app
    depends_on:
      - ackee_db
    environment:
      - ACKEE_MONGODB=mongodb://ackee_db:27017/ackee
      - ACKEE_USERNAME=admin
      - ACKEE_PASSWORD=supersecret
      - ACKEE_PORT=3000
      - ACKEE_ALLOW_ORIGIN=*
      - ACKEE_TRACKER_LOCAL_EVENTS=true
    ports:
      - "8082:3000"
    volumes:
      - ./resources/ackee:/srv/ackee
    restart: unless-stopped